Feature/had 66
ThegwShark/Hades pull request #11
Opened 2024-11-22 05:33 UTC by ThegwShark

2024-11-22 05:47 UTC, 2314-RAustin requested changes

2024-11-22 05:47 UTC, 2314-RAustin commented on src/modules/user/domain/models/user.model.ts
> +  }
Salto de línea, hay que separa cada método o función con un salto de línea para una mejor interpretación de código

2024-11-22 05:47 UTC, 2314-RAustin commented on src/modules/user/domain/models/user.model.ts
> +  }
Salto de línea, hay que separa cada método o función con un salto de línea para una mejor interpretación de código

2024-11-22 05:47 UTC, 2314-RAustin commented on src/modules/user/domain/value-object/user-status.vo.ts
> +export enum Status {
Me parece que esto no es un value object, no sé si hay confusión o aún queda pendiente terminarlo

2024-11-22 05:47 UTC, 2314-RAustin commented on src/modules/user/domain/models/user.model.ts
> +    return this._entityRoot.status;
Aqui tambien deberia ser igual que los otros, no deja de ser un value object

```suggestion
    return this._entityRoot.status._value;
```

2024-11-22 05:47 UTC, 2314-RAustin commented on src/modules/user/domain/models/user.model.ts
> +
Te falto agregar el constructor, aun te quedo duda o porque no se agrego ?

2024-11-26 05:11 UTC, ThegwShark commented on src/modules/user/domain/models/user.model.ts
> +  }
@2314-RAustin Listo, corregido.

2024-11-26 05:13 UTC, ThegwShark commented on src/modules/user/domain/models/user.model.ts
> +  }
@2314-RAustin Listo, corregido.

2024-11-26 05:24 UTC, ThegwShark commented on src/modules/user/domain/value-object/user-status.vo.ts
> +export enum Status {
@2314-RAustin Listo, corregido.

2024-11-26 05:31 UTC, ThegwShark commented on src/modules/user/domain/models/user.model.ts
> +    return this._entityRoot.status;
@2314-RAustin Listo, corregido.

2024-11-26 06:13 UTC, ThegwShark commented on src/modules/user/domain/models/user.model.ts
> +
@2314-RAustin Listo, corregido

2024-11-27 03:36 UTC, 2314-RAustin requested changes

2024-11-27 03:36 UTC, 2314-RAustin commented on src/modules/common/domain/criteria/user-status-enum.ts
> +export enum StatusEnum {
Este archivo lo colocaste ahi aproposito ?
Esta en common y dentro de criteria, este mas bien debe de ir dentro del contexto de dominio de user

2024-11-27 03:36 UTC, 2314-RAustin commented on src/modules/user/domain/models/user.model.ts
> +  }
Salto de línea, hay que separa cada método o función con un salto de línea para una mejor interpretación de código

2024-11-27 03:45 UTC, ThegwShark commented on src/modules/common/domain/criteria/user-status-enum.ts
> +export enum StatusEnum {
@2314-RAustin  Ok, lo modificaré.

2024-11-27 03:46 UTC, ThegwShark commented on src/modules/common/domain/criteria/user-status-enum.ts
> +export enum StatusEnum {
@2314-RAustin Listo, modificado.

2024-11-27 03:51 UTC, ThegwShark commented on src/modules/user/domain/models/user.model.ts
> +  }
@2314-RAustin  Listo, corregido.

2024-11-27 03:53 UTC, 2314-RAustin requested changes

2024-11-27 03:53 UTC, 2314-RAustin commented on src/modules/user/domain/models/user.model.ts
> +  }
Otro salto de linea

2024-11-27 03:55 UTC, 2314-RAustin commented on src/modules/user/domain/enums/user-status-enum.ts
> +export enum StatusEnum {
Creo que te falto borrar los anteriores no ?
Los que se quedaron en common, criteria

2024-11-27 03:58 UTC, ThegwShark commented on src/modules/user/domain/models/user.model.ts
> +  }
@2314-RAustin Listo, corregido.

2024-11-27 03:58 UTC, merged

2024-11-27 03:59 UTC, ThegwShark commented on src/modules/user/domain/enums/user-status-enum.ts
> +export enum StatusEnum {
@2314-RAustin Si, fue eliminado. Chécalo de nuevo.