Feature/had 121
ThegwShark/Hades pull request #24
Opened 2024-12-11 05:32 UTC by ThegwShark

2024-12-11 07:01 UTC, 2314-RAustin commented
Faltan parámetros para crear la sesión como tal, algunos campos de la tabla son calculables y otros no, adjunto documentación de la descripción de cada campo.

https://innovationsmi.atlassian.net/wiki/spaces/Hades/pages/194740234/Sessions

2024-12-12 05:19 UTC, 2314-RAustin requested changes

2024-12-12 05:19 UTC, 2314-RAustin commented on src/modules/user/infrastructure/controllers/session/commands/create-session/create-session-input.dto.ts
> +  @Length(5, 255)
Para todas las longitudes maneja el archivo de reglas, hay ejemplos en los otros controladores

2024-12-12 05:19 UTC, 2314-RAustin commented on src/modules/user/infrastructure/controllers/session/commands/create-session/create-session-output.dto.ts
> +  public readonly uuid: string;
Falta el id

2024-12-13 04:47 UTC, ThegwShark commented on src/modules/user/infrastructure/controllers/session/commands/create-session/create-session-input.dto.ts
> +  @Length(5, 255)
@2314-RAustin Listo, corregido.

2024-12-13 04:49 UTC, ThegwShark commented on src/modules/user/infrastructure/controllers/session/commands/create-session/create-session-output.dto.ts
> +  public readonly uuid: string;
@2314-RAustin Listo, corregido.

2024-12-13 18:28 UTC, 2314-RAustin approved these changes

2024-12-13 18:29 UTC, merged